### PR TITLE
Fix path to an example directory

### PR DESCRIPTION
**Pull request by jan-kolarik**
The batch job example cannot be completed without the correct PV host path.

### CODE REVIEW

**Comment by rhuss** [comment]
I'm not sure why this should fix any issue with the example, as the hostPath `/example` usually does not exist and you don't have write permissions in the root fs directory.

Can you elaborate a bit what issue you are facing (including the error message) with the original path of `/tmp/example` ?

Thanks!

**Comment by jan-kolarik** [comment]
> I'm not sure why this should fix any issue with the example, as the hostPath `/example` usually does not exist and you don't have write permissions in the root fs directory.
> 
> Can you elaborate a bit what issue you are facing (including the error message) with the original path of `/tmp/example` ?
> 
> Thanks!

Sure!

So, I'm creating the Minikube cluster from scratch using the command provided in the README from the BatchJob example:

```
minikube start --mount --mount-string="$(pwd)/logs:/example"
```

After applying the `pv-and-pvc.yml` resources, when I create the pods from `job.yml`, they enter the Error status. When I check the pod logs, I see the following error message:

```
Exception in thread "main" java.io.FileNotFoundException: /tmp/logs/random.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at RandomRunner.appendLineWithLocking(RandomRunner.java:73)
	at RandomRunner.main(RandomRunner.java:53)
```

If the path is changed as I suggest, everything works fine.

**Comment by jan-kolarik** [comment]
Hmm, so maybe it would be better to just edit that README to match e.g. the PeriodicJob:

```
minikube start --mount --mount-string="$(pwd)/logs:/tmp/example"
```

I've created a new [PR](https://github.com/k8spatterns/examples/pull/58) for that.

**Comment by rhuss** [comment]
Yes, this makes totally sense. Many thanks, I'm going to merge the README-PR ...

**Pull request closed without merging**
